name: Upload Static Website to S3

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2  # Use version 2 of the checkout action

      # Step 2: Install dependencies (only if needed, e.g., for a Node.js or static site generator)
      - name: Install dependencies
        run: |
          npm install  # Or use 'yarn install' if using Yarn

      # Step 3: Build the static site
      - name: Build the static website
        run: |
          npm run build  # Replace this with the build command for your static site generator, e.g., 'gatsby build', 'hugo', 'next build', etc.

      # Step 4: Verify that the build output directory exists
      - name: Check if build directory exists
        run: |
          if [ ! -d "public" ]; then
            echo "Error: The 'public' directory does not exist. Exiting."
            exit 1  # Exit the workflow if the directory doesn't exist
          fi

      # Step 5: Sync the static files to S3
      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete  # Optional: public-read for public files, --delete to remove files no longer present
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'  # Replace with your AWS region (default is us-east-1)
          SOURCE_DIR: 'public'  # Directory containing the built static files

