    name: Deploy Static Site to AWS S3

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2' # Specify your AWS region

      # Sync static files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./assets/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

      # Invalidate CloudFront cache (Optional, if using CloudFront)
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3MKQIUBE8J2YH --paths "/*"
