name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optional: Install dependencies and run build (if applicable)
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Ensure this creates the 'build/public' directory

      # Step 1: Check if the 'source_dir' exists
      - name: Check if source_dir exists
        run: |
          if [ ! -d "./build/public" ]; then
            echo "Error: Source directory ./build/public does not exist"
            exit 1
          fi

      # Step 2: Sync files to S3
      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-2'
          s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: './build/public'  # Make sure this path is correct
          acl: 'public-read'
          delete: true
