name: Deploy Static Site to S3

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (you can change the branch name)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI (using GitHub secrets for AWS credentials)
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Make sure the region is set in GitHub secrets

     # Sync static files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./assets/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
     
